### ISSUE TITLE
Uncaught TypeError: this.debouncedEndStreak is not a function

### ISSUE THREAD

**Issue by Leask** [JoelBesada/activate-power-mode#280]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.13
**Thrown From**: [activate-power-mode](https://github.com/JoelBesada/activate-power-mode) package 2.0.0

### Stack Trace

Uncaught TypeError: this.debouncedEndStreak is not a function

```
At /Users/leask/Documents/.flora/mackup/.atom/packages/activate-power-mode/lib/combo-renderer.coffee:101

TypeError: this.debouncedEndStreak is not a function
    at Object.modifyStreak (/packages/activate-power-mode/lib/combo-renderer.coffee:101:6)
    at Object.onInput (/packages/activate-power-mode/lib/plugin/combo-mode.coffee:25:12)
    at /packages/activate-power-mode/lib/plugin-manager.coffee:103:16
    at Object.onEnabled (/packages/activate-power-mode/lib/plugin-registry.coffee:64:19)
    at Object.runOnInput (/packages/activate-power-mode/lib/plugin-manager.coffee:100:21)
    at /packages/activate-power-mode/lib/power-editor.coffee:54:22
```

### Commands

```
     -0:05.7.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:05.3.0 vim-mode-plus:substitute (input.hidden-input)
  5x -0:04.1.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.0.0 
atom-alignment 0.13.0 
atom-beautify 0.29.24 
busy-signal 1.4.3 
color-picker 2.2.5 
file-icons 2.1.7 
git-time-machine 1.5.9 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.6.1 
minimap 4.28.2 
multi-wrap-guide 0.28.4 
node-debugger 1.10.1 
pigments 0.39.1 
pretty-json 1.6.3 
tabs-to-spaces 1.0.3 
vim-mode-plus 0.93.0 
wakatime 7.0.3 
```

**Comment by lexcast** [comment]
Hi @Leask, Does this happens when vim-mode is disabled?

**Comment by Leask** [comment]
It works on v1.20 currently, thanks!
